[package]
name = "HelloBlockchain"
version = "1.0.0"
authors = []

[addresses]
hello_blockchain = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
