name: Run bin script on Mac

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the bin script on Mac
        run: |
          npm install
          npm run build
          node ./dist/aptos.js
